// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: LedCubeDisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_main_screen;
void ui_event_back_button(lv_event_t * e);
lv_obj_t * ui_back_button;
lv_obj_t * ui_back_image;
void ui_event_play_button(lv_event_t * e);
lv_obj_t * ui_play_button;
lv_obj_t * ui_play_image;
lv_obj_t * ui_animation_text;
void ui_event_forward_button(lv_event_t * e);
lv_obj_t * ui_forward_button;
lv_obj_t * ui_forward_image;
lv_obj_t * ui_ota_screen;
lv_obj_t * ui_ota_device_name_text;
lv_obj_t * ui_ota_text;
lv_obj_t * ui_progress_bar;
lv_obj_t * ui_progress_text;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_back_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backButtonPressed(e);
    }
}
void ui_event_play_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_play_image, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_pause_png);
        _ui_basic_set_property(ui_play_image, _UI_BASIC_PROPERTY_POSITION_X,  0);
        playButtonPressed(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_play_image, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_play_png);
        _ui_basic_set_property(ui_play_image, _UI_BASIC_PROPERTY_POSITION_X,  2);
        pauseButtonPressed(e);
    }
}
void ui_event_forward_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        forwardButtonPressed(e);
    }
}

///////////////////// SCREENS ////////////////////
void ui_main_screen_screen_init(void)
{
    ui_main_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_back_button = lv_btn_create(ui_main_screen);
    lv_obj_set_width(ui_back_button, 50);
    lv_obj_set_height(ui_back_button, 50);
    lv_obj_set_x(ui_back_button, 35);
    lv_obj_set_y(ui_back_button, -20);
    lv_obj_set_align(ui_back_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_back_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_back_button, lv_color_hex(0x474655), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_back_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_image = lv_img_create(ui_back_button);
    lv_img_set_src(ui_back_image, &ui_img_backward_png);
    lv_obj_set_width(ui_back_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_back_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_back_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_back_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_play_button = lv_btn_create(ui_main_screen);
    lv_obj_set_width(ui_play_button, 70);
    lv_obj_set_height(ui_play_button, 70);
    lv_obj_set_x(ui_play_button, 0);
    lv_obj_set_y(ui_play_button, -10);
    lv_obj_set_align(ui_play_button, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_play_button, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_play_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_play_button, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_play_button, lv_color_hex(0x474655), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_play_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_play_button, lv_color_hex(0x474655), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_play_button, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_play_image = lv_img_create(ui_play_button);
    lv_img_set_src(ui_play_image, &ui_img_pause_png);
    lv_obj_set_width(ui_play_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_play_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_play_image, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_play_image, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_play_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_play_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_play_image, 400);

    ui_animation_text = lv_label_create(ui_main_screen);
    lv_obj_set_width(ui_animation_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_animation_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_animation_text, 0);
    lv_obj_set_y(ui_animation_text, 31);
    lv_obj_set_align(ui_animation_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_animation_text, "Animation");
    lv_obj_set_style_text_font(ui_animation_text, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forward_button = lv_btn_create(ui_main_screen);
    lv_obj_set_width(ui_forward_button, 50);
    lv_obj_set_height(ui_forward_button, 50);
    lv_obj_set_x(ui_forward_button, -35);
    lv_obj_set_y(ui_forward_button, -20);
    lv_obj_set_align(ui_forward_button, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_forward_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_forward_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_forward_button, lv_color_hex(0x474655), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_forward_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forward_image = lv_img_create(ui_forward_button);
    lv_img_set_src(ui_forward_image, &ui_img_forward_png);
    lv_obj_set_width(ui_forward_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_forward_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_forward_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forward_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forward_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_back_button, ui_event_back_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_play_button, ui_event_play_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_forward_button, ui_event_forward_button, LV_EVENT_ALL, NULL);

}
void ui_ota_screen_screen_init(void)
{
    ui_ota_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ota_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ota_device_name_text = lv_label_create(ui_ota_screen);
    lv_obj_set_width(ui_ota_device_name_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ota_device_name_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ota_device_name_text, 0);
    lv_obj_set_y(ui_ota_device_name_text, -57);
    lv_obj_set_align(ui_ota_device_name_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ota_device_name_text, "Led Cube");
    lv_obj_set_style_text_font(ui_ota_device_name_text, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ota_text = lv_label_create(ui_ota_screen);
    lv_obj_set_width(ui_ota_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ota_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ota_text, 0);
    lv_obj_set_y(ui_ota_text, -28);
    lv_obj_set_align(ui_ota_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ota_text, "Over the Air Update");
    lv_obj_set_style_text_font(ui_ota_text, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_progress_bar = lv_bar_create(ui_ota_screen);
    lv_obj_set_width(ui_progress_bar, 293);
    lv_obj_set_height(ui_progress_bar, 46);
    lv_obj_set_x(ui_progress_bar, 2);
    lv_obj_set_y(ui_progress_bar, 23);
    lv_obj_set_align(ui_progress_bar, LV_ALIGN_CENTER);

    ui_progress_text = lv_label_create(ui_progress_bar);
    lv_obj_set_width(ui_progress_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_progress_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_progress_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_progress_text, "0%");
    lv_obj_set_style_text_color(ui_progress_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_progress_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_progress_text, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_screen_init();
    ui_ota_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main_screen);
}
