// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: LedCubeDisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_rotary_screen
void ui_rotary_screen_screen_init(void);
lv_obj_t * ui_rotary_screen;
lv_obj_t * ui_animation_text_large;
lv_obj_t * ui_fps_text;

// SCREEN: ui_main_screen
void ui_main_screen_screen_init(void);
lv_obj_t * ui_main_screen;
void ui_event_back_button(lv_event_t * e);
lv_obj_t * ui_back_button;
lv_obj_t * ui_back_image;
void ui_event_play_button(lv_event_t * e);
lv_obj_t * ui_play_button;
lv_obj_t * ui_play_image;
lv_obj_t * ui_animation_text;
void ui_event_forward_button(lv_event_t * e);
lv_obj_t * ui_forward_button;
lv_obj_t * ui_forward_image;

// SCREEN: ui_ota_screen
void ui_ota_screen_screen_init(void);
lv_obj_t * ui_ota_screen;
lv_obj_t * ui_ota_device_name_text;
lv_obj_t * ui_ota_text;
lv_obj_t * ui_progress_bar;
lv_obj_t * ui_progress_text;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_back_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backButtonPressed(e);
    }
}
void ui_event_play_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_play_image, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_pause_png);
        _ui_basic_set_property(ui_play_image, _UI_BASIC_PROPERTY_POSITION_X,  0);
        playButtonPressed(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_play_image, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_play_png);
        _ui_basic_set_property(ui_play_image, _UI_BASIC_PROPERTY_POSITION_X,  2);
        pauseButtonPressed(e);
    }
}
void ui_event_forward_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        forwardButtonPressed(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_rotary_screen_screen_init();
    ui_main_screen_screen_init();
    ui_ota_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_rotary_screen);
}
