// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: LedCubeDisplay

#ifndef _LEDCUBEDISPLAY_UI_H
#define _LEDCUBEDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_rotary_screen
void ui_rotary_screen_screen_init(void);
extern lv_obj_t * ui_rotary_screen;
extern lv_obj_t * ui_animation_text_large;
extern lv_obj_t * ui_fps_text;
// SCREEN: ui_main_screen
void ui_main_screen_screen_init(void);
extern lv_obj_t * ui_main_screen;
void ui_event_back_button(lv_event_t * e);
extern lv_obj_t * ui_back_button;
extern lv_obj_t * ui_back_image;
void ui_event_play_button(lv_event_t * e);
extern lv_obj_t * ui_play_button;
extern lv_obj_t * ui_play_image;
extern lv_obj_t * ui_animation_text;
void ui_event_forward_button(lv_event_t * e);
extern lv_obj_t * ui_forward_button;
extern lv_obj_t * ui_forward_image;
// SCREEN: ui_ota_screen
void ui_ota_screen_screen_init(void);
extern lv_obj_t * ui_ota_screen;
extern lv_obj_t * ui_ota_device_name_text;
extern lv_obj_t * ui_ota_text;
extern lv_obj_t * ui_progress_bar;
extern lv_obj_t * ui_progress_text;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_backward_png);    // assets\backward.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets\pause.png
LV_IMG_DECLARE(ui_img_play_png);    // assets\play.png
LV_IMG_DECLARE(ui_img_forward_png);    // assets\forward.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
