// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: LedCubeDisplay

#ifndef _LEDCUBEDISPLAY_UI_H
#define _LEDCUBEDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
void ui_event_backButton(lv_event_t * e);
extern lv_obj_t * ui_backButton;
extern lv_obj_t * ui_backImage;
void ui_event_playButton(lv_event_t * e);
extern lv_obj_t * ui_playButton;
extern lv_obj_t * ui_playImage;
extern lv_obj_t * ui_aninmationText;
void ui_event_forwardButton(lv_event_t * e);
extern lv_obj_t * ui_forwardButton;
extern lv_obj_t * ui_forwardImage;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_backward_png);    // assets\backward.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets\pause.png
LV_IMG_DECLARE(ui_img_play_png);    // assets\play.png
LV_IMG_DECLARE(ui_img_forward_png);    // assets\forward.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
