// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: LedCubeDisplay

#include "../ui.h"

void ui_main_screen_screen_init(void)
{
    ui_main_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_back_button = lv_btn_create(ui_main_screen);
    lv_obj_set_width(ui_back_button, 50);
    lv_obj_set_height(ui_back_button, 50);
    lv_obj_set_x(ui_back_button, 35);
    lv_obj_set_y(ui_back_button, -20);
    lv_obj_set_align(ui_back_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_back_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_back_button, lv_color_hex(0x474655), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_back_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_image = lv_img_create(ui_back_button);
    lv_img_set_src(ui_back_image, &ui_img_backward_png);
    lv_obj_set_width(ui_back_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_back_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_back_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_back_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_play_button = lv_btn_create(ui_main_screen);
    lv_obj_set_width(ui_play_button, 70);
    lv_obj_set_height(ui_play_button, 70);
    lv_obj_set_x(ui_play_button, 0);
    lv_obj_set_y(ui_play_button, -10);
    lv_obj_set_align(ui_play_button, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_play_button, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_play_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_play_button, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_play_button, lv_color_hex(0x474655), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_play_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_play_button, lv_color_hex(0x474655), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_play_button, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_play_image = lv_img_create(ui_play_button);
    lv_img_set_src(ui_play_image, &ui_img_pause_png);
    lv_obj_set_width(ui_play_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_play_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_play_image, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_play_image, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_play_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_play_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_play_image, 400);

    ui_animation_text = lv_label_create(ui_main_screen);
    lv_obj_set_width(ui_animation_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_animation_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_animation_text, 0);
    lv_obj_set_y(ui_animation_text, 31);
    lv_obj_set_align(ui_animation_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_animation_text, "Animation");
    lv_obj_set_style_text_font(ui_animation_text, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forward_button = lv_btn_create(ui_main_screen);
    lv_obj_set_width(ui_forward_button, 50);
    lv_obj_set_height(ui_forward_button, 50);
    lv_obj_set_x(ui_forward_button, -35);
    lv_obj_set_y(ui_forward_button, -20);
    lv_obj_set_align(ui_forward_button, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_forward_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_forward_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_forward_button, lv_color_hex(0x474655), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_forward_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forward_image = lv_img_create(ui_forward_button);
    lv_img_set_src(ui_forward_image, &ui_img_forward_png);
    lv_obj_set_width(ui_forward_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_forward_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_forward_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forward_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forward_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_back_button, ui_event_back_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_play_button, ui_event_play_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_forward_button, ui_event_forward_button, LV_EVENT_ALL, NULL);

}
