// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: LedCubeDisplay

#include "../ui.h"

void ui_rotary_screen_screen_init(void)
{
    ui_rotary_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_rotary_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_animation_text_large = lv_label_create(ui_rotary_screen);
    lv_obj_set_width(ui_animation_text_large, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_animation_text_large, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_animation_text_large, 0);
    lv_obj_set_y(ui_animation_text_large, 64);
    lv_obj_set_align(ui_animation_text_large, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_animation_text_large, "Animation");
    lv_obj_set_style_text_font(ui_animation_text_large, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fps_text = lv_label_create(ui_rotary_screen);
    lv_obj_set_width(ui_fps_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fps_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fps_text, 5);
    lv_obj_set_y(ui_fps_text, 5);
    lv_label_set_text(ui_fps_text, "");
    lv_obj_set_style_text_font(ui_fps_text, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
