// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: LedCubeDisplay

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void backButtonPressed(lv_event_t * e);
void playButtonPressed(lv_event_t * e);
void pauseButtonPressed(lv_event_t * e);
void forwardButtonPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
